const books_cs = {
    "1Chr": "1 Pa",
    "1Cor": "1 Kor",
    "1John": "1 J",
    "1Kgs": "1 Kr",
    "1Macc": "1 Mak",
    "1Pet": "1 P",
    "1Sam": "1 S",
    "1Thess": "1 Te",
    "1Tim": "1 Tim",
    "2Chr": "2 Pa",
    "2Cor": "2 Kor",
    "2John": "2 J",
    "2Kgs": "2 Kr",
    "2Macc": "2 Mak",
    "2Pet": "2 P",
    "2Sam": "2 S",
    "2Thess": "2 Te",
    "2Tim": "2 Tim",
    "3John": "3 J",
    "3Macc": "3 Mak",
    "4Macc": "4 Mak",
    "Acts": "Sk",
    "Amos": "Am",
    "Bar": "Bar",
    "Col": "Col",
    "Dan": "Dan",
    "Deut": "Dt",
    "Eccl": "Kaz",
    "Eph": "Ef",
    "Esth": "Est",
    "Exod": "Ex",
    "Ezek": "Ez",
    "Ezra": "Ezd",
    "Gal": "Gal",
    "Gen": "Gn",
    "Hab": "Hab",
    "Hag": "Ag",
    "Heb": "Žd",
    "Hos": "Oz",
    "Isa": "Iz",
    "Jas": "Jk",
    "Jdt": "Júd",
    "Jer": "Jr",
    "Job": "Job",
    "Joel": "Jo",
    "John": "J",
    "Jonah": "Jon",
    "Josh": "Joz",
    "Jude": "Jd",
    "Judg": "Sdc",
    "Lam": "Pl",
    "Lev": "Lv",
    "Luke": "L",
    "Mal": "Mal",
    "Mark": "Mk",
    "Matt": "Mt",
    "Mic": "Mi",
    "Nah": "Nah",
    "Neh": "Neh",
    "Num": "Nu",
    "Obad": "Abd",
    "Phil": "Fp",
    "Phlm": "Fm",
    "Prov": "Př",
    "Ps": "Ž",
    "Rev": "Zj",
    "Rom": "Řím",
    "Ruth": "Rút",
    "Sir": "Sir",
    "Song": "Pís",
    "Titus": "Tit",
    "Tob": "Tob",
    "Wis": "Mdr",
    "Zech": "Za",
    "Zeph": "Sf"
}

module.exports = {
    books_cs: books_cs,
    getCzechBookName: function(book) {
        return books_cs[book];
    }
}